"""Keywords for asserting on a downloaded .xlsx without any third-party dependency.

The Council membership report is generated by injecting values into the Council's own
template, so these keywords read the raw SpreadsheetML rather than using a spreadsheet
library — that way the tests can also assert the template's own parts came through
untouched, which is the property that actually matters for this report.
"""
import xml.etree.ElementTree as ET
import zipfile

NS = '{http://schemas.openxmlformats.org/spreadsheetml/2006/main}'

# The Council's NATIONAL tab is the first worksheet in the workbook.
NATIONAL_SHEET = 'xl/worksheets/sheet1.xml'


class XlsxInspector:
    ROBOT_LIBRARY_SCOPE = 'GLOBAL'

    def _sheet_xml(self, path, entry=NATIONAL_SHEET):
        with zipfile.ZipFile(path) as archive:
            return archive.read(entry).decode('utf-8')

    def _shared_strings(self, path):
        with zipfile.ZipFile(path) as archive:
            if 'xl/sharedStrings.xml' not in archive.namelist():
                return []
            root = ET.fromstring(archive.read('xl/sharedStrings.xml'))
        return [''.join(t.text or '' for t in si.iter(NS + 't')) for si in root.findall(NS + 'si')]

    def xlsx_should_be_a_valid_workbook(self, path):
        """Fail unless every XML part parses and the expected sheets are present."""
        with zipfile.ZipFile(path) as archive:
            names = archive.namelist()
            for name in names:
                if name.endswith('.xml') or name.endswith('.rels'):
                    ET.fromstring(archive.read(name))
        for required in (NATIONAL_SHEET, 'xl/styles.xml', 'xl/workbook.xml'):
            if required not in names:
                raise AssertionError(f'{path} is missing {required}')
        return names

    def get_xlsx_cell(self, path, ref):
        """Return the text of one cell of the NATIONAL sheet ('' when the cell is empty)."""
        shared = self._shared_strings(path)
        root = ET.fromstring(self._sheet_xml(path))
        for cell in root.iter(NS + 'c'):
            if cell.get('r') != ref:
                continue
            inline = cell.find(NS + 'is')
            if inline is not None:
                return ''.join(t.text or '' for t in inline.iter(NS + 't'))
            value = cell.find(NS + 'v')
            if value is None or value.text is None:
                return ''
            if cell.get('t') == 's':
                return shared[int(value.text)]
            return value.text
        raise AssertionError(f'Cell {ref} not found in {path}')

    def xlsx_cell_should_be(self, path, ref, expected):
        actual = self.get_xlsx_cell(path, ref)
        if actual != expected:
            raise AssertionError(f'Cell {ref} was {actual!r}, expected {expected!r}')

    def get_xlsx_sheet_names(self, path):
        with zipfile.ZipFile(path) as archive:
            root = ET.fromstring(archive.read('xl/workbook.xml'))
        return [sheet.get('name') for sheet in root.iter(NS + 'sheet')]

    def get_xlsx_data_rows(self, path, first_row=19, columns='BCDEFGHIJKL'):
        """Return the populated data rows as lists of strings, stopping at the first blank."""
        rows = []
        row = int(first_row)
        while True:
            values = [self.get_xlsx_cell(path, f'{col}{row}') for col in columns]
            if not any(values):
                return rows
            rows.append(values)
            row += 1

    def xlsx_should_match_template_formatting(self, path, template_path):
        """Fail unless every part except the NATIONAL sheet is byte-identical to the template.

        This is the guard on "exact formatting": styles, theme, print settings and the
        other Council tabs must survive generation unchanged.
        """
        with zipfile.ZipFile(template_path) as template, zipfile.ZipFile(path) as generated:
            produced = set(generated.namelist())
            differing = []
            for name in template.namelist():
                if name.endswith('/'):
                    continue
                if name not in produced:
                    differing.append(f'{name} (missing)')
                elif name != NATIONAL_SHEET and template.read(name) != generated.read(name):
                    differing.append(f'{name} (differs)')
        if differing:
            raise AssertionError('Workbook diverged from the Council template: ' + ', '.join(differing))
